name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run Linter
    defaults:
      run:
        shell: bash
        # Defines the working directory for all run steps in the workflow
        # working-directory: ./src
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    - name: 'Install Dependencies'
      run: npm install
    - name: 'Run Linter'
      run: npx standard -v
